class PaymentGatewayError(Exception): ...

class InitiatePaymentResponse:
    redirect_url: str
    provider_reference: str
    raw: str
    request_id: str | None

class VerifyPaymentResponse:
    status: str
    provider_reference: str
    amount: str | None
    currency: str | None
    raw: str
    request_id: str | None

class RefundResponse:
    status: str
    provider_reference: str
    raw: str
    request_id: str | None

class ShurjopayClient:
    def __init__(self, config_json: str) -> None: ...
    def initiate_payment(self, request_json: str) -> InitiatePaymentResponse: ...
    def verify_payment(self, request_json: str) -> VerifyPaymentResponse: ...

class PortwalletClient:
    def __init__(self, config_json: str) -> None: ...
    def initiate_payment(self, request_json: str) -> InitiatePaymentResponse: ...
    def verify_payment(self, request_json: str) -> VerifyPaymentResponse: ...
    def refund(self, request_json: str) -> RefundResponse: ...

class AamarpayClient:
    def __init__(self, config_json: str) -> None: ...
    def initiate_payment(self, request_json: str) -> InitiatePaymentResponse: ...
    def verify_payment(self, request_json: str) -> VerifyPaymentResponse: ...

class SslcommerzClient:
    def __init__(self, config_json: str) -> None: ...
    def initiate_payment(self, request_json: str) -> InitiatePaymentResponse: ...
    def verify_payment(self, request_json: str) -> VerifyPaymentResponse: ...
    def refund(self, request_json: str) -> RefundResponse: ...
